ALTER TABLE pets ADD COLUMN IF NOT EXISTS breed TEXT;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS color TEXT;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS features TEXT;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS chip_id TEXT;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS stamp_id TEXT;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS photo_url TEXT;

-- Маркеры пропуска необязательных полей
ALTER TABLE pets ADD COLUMN IF NOT EXISTS breed_skipped BOOLEAN DEFAULT FALSE;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS color_skipped BOOLEAN DEFAULT FALSE;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS features_skipped BOOLEAN DEFAULT FALSE;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS chip_skipped BOOLEAN DEFAULT FALSE;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS stamp_skipped BOOLEAN DEFAULT FALSE;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS photo_skipped BOOLEAN DEFAULT FALSE;
